# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: course.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'course.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ourse.proto\x12\x06\x63ourse\"\x1d\n\x0f\x43ourseIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"L\n\x13\x43reateCourseRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nteacher_id\x18\x03 \x01(\x05\"S\n\x0e\x43ourseResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nteacher_id\x18\x04 \x01(\x05\"\x07\n\x05\x45mpty2\xca\x01\n\rCourseService\x12<\n\tGetCourse\x12\x17.course.CourseIdRequest\x1a\x16.course.CourseResponse\x12\x43\n\x0c\x43reateCourse\x12\x1b.course.CreateCourseRequest\x1a\x16.course.CourseResponse\x12\x36\n\x0c\x44\x65leteCourse\x12\x17.course.CourseIdRequest\x1a\r.course.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COURSEIDREQUEST']._serialized_start=24
  _globals['_COURSEIDREQUEST']._serialized_end=53
  _globals['_CREATECOURSEREQUEST']._serialized_start=55
  _globals['_CREATECOURSEREQUEST']._serialized_end=131
  _globals['_COURSERESPONSE']._serialized_start=133
  _globals['_COURSERESPONSE']._serialized_end=216
  _globals['_EMPTY']._serialized_start=218
  _globals['_EMPTY']._serialized_end=225
  _globals['_COURSESERVICE']._serialized_start=228
  _globals['_COURSESERVICE']._serialized_end=430
# @@protoc_insertion_point(module_scope)
