# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enrollment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'enrollment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65nrollment.proto\x12\nenrollment\"6\n\rEnrollRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\x12\x11\n\tcourse_id\x18\x02 \x01(\x05\"8\n\x0e\x45nrollResponse\x12\x15\n\renrollment_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x0f\x43ourseIdRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\"<\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nstudent_id\x18\x02 \x01(\x05\x12\x11\n\tcourse_id\x18\x03 \x01(\x05\"<\n\x13StudentListResponse\x12%\n\x08students\x18\x01 \x03(\x0b\x32\x13.enrollment.Student2\xb0\x01\n\x11\x45nrollmentService\x12\x46\n\rEnrollStudent\x12\x19.enrollment.EnrollRequest\x1a\x1a.enrollment.EnrollResponse\x12S\n\x13GetEnrolledStudents\x12\x1b.enrollment.CourseIdRequest\x1a\x1f.enrollment.StudentListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enrollment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENROLLREQUEST']._serialized_start=32
  _globals['_ENROLLREQUEST']._serialized_end=86
  _globals['_ENROLLRESPONSE']._serialized_start=88
  _globals['_ENROLLRESPONSE']._serialized_end=144
  _globals['_COURSEIDREQUEST']._serialized_start=146
  _globals['_COURSEIDREQUEST']._serialized_end=182
  _globals['_STUDENT']._serialized_start=184
  _globals['_STUDENT']._serialized_end=244
  _globals['_STUDENTLISTRESPONSE']._serialized_start=246
  _globals['_STUDENTLISTRESPONSE']._serialized_end=306
  _globals['_ENROLLMENTSERVICE']._serialized_start=309
  _globals['_ENROLLMENTSERVICE']._serialized_end=485
# @@protoc_insertion_point(module_scope)
